FROM python:3.11.4

# Install Poetry
RUN pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

COPY ./ ./

# Make port 8000 available to the world outside this container
EXPOSE 80

# Run Main.py when the container launches
CMD ["python3", "main.py"]
